language: generic
os: osx
osx_image: xcode8.1
branches:
  only:
  - master
before_install:
- export XCODEBUILD_PATH=$(which xcodebuild)
- export PATH=$PATH:$XCODEBUILD_PATH
- export PATH=$PATH:~/bin
install:
- gem install xcpretty --user-install -n~/bin
script:
- go run Testing/tests.go
