language: generic
os: osx
osx_image: xcode7.3
before_install:
- export XCODEBUILD_PATH=$(which xcodebuild)
- export PATH=$PATH:$XCODEBUILD_PATH
install:
- git submodule init
- git submodule update

script:
- go run script/tests.go
